[package]
name = "aoc2023_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.10", features = ["derive"] }
curl = "0.4.44"
md5 = "0.7.0"
num-rational = "0.4.1"
rayon = "1.8.0"
regex = "1.10.2"
